import Head from 'next/head'
import Image from "next/image";
import { Slide } from 'react-slideshow-image';
import { useState, useEffect, useRef} from 'react'

function Home() {

  const [memes, setMeme] = useState()
  const [value, setValue] = useState(4)

  useEffect(() =>{
    fetch('https://api.imgflip.com/get_memes')
      .then((res) => res.json())
      .then((value) => value.data.memes)
      .then((data) => data.filter((meme) => meme.box_count == value))
      .then(memes =>{
        setMeme(memes)
      })
  },[value])

  function handleClick(value) {
    setValue(value)
  }

  return (
    <div>
      <Head>
        <title>Meme land</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-black'>
        <section className='w-full h-full md:h-screen
                            bg-white bg-opacity-50 backdrop-blur-xl'>
          <div className='flex justify-center'>
            <ImageSlide slideImages={memes} />
          </div>

          <h1 className='flex justify-around my-5 font-bold'>
              Choose by box_count
          </h1>

          <div className='flex justify-around'>
              {[2,3,4,5].map((value, index) => (
                <Option box_count={value} key={index} onClick={value => handleClick(value)}/>
              ))}
            </div>
        </section>
      </main>
    </div>
  )
}

function Option(props){

  return(
    <button className='bg-blue-500 hover:bg-blue-700
                       text-white font-bold py-2 w-32 rounded'
            onClick={() => props.onClick(props.box_count)}
    >
      {props.box_count}
    </button>
  )
}

function ImageSlide({slideImages}){

  const slideRef = useRef();

  useEffect(()=> {
    if(slideRef.current != undefined)
      slideRef.current.goTo(0)
  },[slideImages])

  if(!slideImages) return(<div className="slide-container w-full h-96 md:max-w-7xl"></div>)

  return(
    <div className="slide-container w-full ">
            <Slide
            infinite={false}
            indicators={true}
            ref={slideRef}
              >
                {slideImages.map((slideImage, index)=> (
                    <div className="each-slide" key={index}>
                        <div className='w-full flex justify-center
                        bg-white bg-opacity-70 bg-cover image-contain'>
                            <Image src={slideImage.url}
                                   alt={slideImage.name}
                                   className="object-contain min-w-fit"
                                   width={slideImage.width}
                                   height={slideImage.height}
                                   loading="lazy"/>
                        </div>
                        <div className='flex justify-center'>
                          <h1 className='font-bold uppercase'>{slideImage.name}</h1>
                        </div>
                    </div>
                ))}
            </Slide>
    </div>
)
}

export default Home;